// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqmtubgqmfkypsbonfhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxbXR1YmdxbWZreXBzYm9uZmhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwODkzNzIsImV4cCI6MjA2NjY2NTM3Mn0.t9t-ZInYlOcAy61HxpYhmMplVx2a2YX-pzh6uOUsOsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});